### ISSUE TITLE
add data structures/algorithms that have been covered in Readme.md

### ISSUE THREAD

**Issue by sandesh-theMayGuy** [sandesh-theMayGuy/DSA-in-C-CPP#23]
Edit Readme.md and add data structures/algorithms that have been covered (already present in repository) along with the language in which they got implemented

Eg: 
Data Structures that have been covered:
Stack(C)
Queue(C)

Algorithms that have been covered:
MergeSort(C)
Quick Sort(C++)

**Comment by shubha987** [comment]
please assign me the issue..
