### ISSUE TITLE
Move Doubly_Linked_List.c inside "C" folder and add Data Structure/Algorithms that has been covered in Readme.md

### ISSUE THREAD

**Issue by sandesh-theMayGuy** [sandesh-theMayGuy/DSA-in-C-CPP#51]
Doubly_Linked_List.c is in root directory. That needs to be moved inside "C" directory.

And, Readme.md needs to be updated with new data structures and algorithms that have been covered/added to the repo.
Please have a look inside both "C" and "C++" directories and update Readme.md accordingly

**Comment by shubha987** [comment]
@sandesh-theMayGuy assign it to me
